Fetch internal IPs of vms from dhcp server
openshift/cloud-provider-powervs pull request #10
Opened 2022-05-05 10:51 UTC by Karthik-K-N

This PR contains the changes to fetch the internal ips of vms from dhscp server if `powerVSDhcpServerID` is provided in cloud-config.

This change will introduce two new parameters to cloud-conf

1. `powerVSDhcpServerID` : This is the dhcp server id located in a power vs service instance, This is used to query the dhcp leases and find the appropriate node ips.
If this is empty, ccm will try to fetch the ips from `pvsInstance.Networks` field.

2. `powerVSVMNetworkName` : This is the network name that i attached to Power VS VM. This is used to get the mac to find the appropriate dhcp lease.

2022-05-05 10:52 UTC, Karthik-K-N commented
@mkumatag @dharaneeshvrd  I have tried this way to fetch the IPs from dhcp server, Please take look

2022-07-19 13:52 UTC, Karthik-K-N commented
@mkumatag @dharaneeshvrd Please take a look

2022-07-20 07:18 UTC, dharaneeshvrd commented on ibm/caching.go
> +const CacheTTL = time.Duration(15) * time.Minute
If it is not used outside of this package, no need to export it I guess.

2022-07-21 08:13 UTC, dharaneeshvrd commented
Changes look good to me!

2022-07-21 09:58 UTC, Karthik-K-N commented
The Nodemetada is fetched once in every 5 minutes, eventhough there is an error while fetching it for a node , the next try to fetch the metadata is after 5 minutes only, In general irrespective of success or failure on fetching nodemetadata the sycnh is done once in 5 minutes

2022-07-21 09:59 UTC, mkumatag requested changes
As discussed lets have a code to skip if the dhcp query if network is not managed by dhcp

2022-07-22 08:18 UTC, mkumatag requested changes

2022-07-22 08:18 UTC, mkumatag commented on ibm/ibm_powervs_client.go
> +func (p *ibmPowerVSClient) getPowerVSNetwork(instance *models.PVMInstance) (*models.PVMInstanceNetwork, error) {
can this be non-struct method and add some UT around it?

2022-07-22 09:51 UTC, mkumatag approved these changes
/lgtm

2022-07-22 10:10 UTC, merged

2022-07-27 11:23 UTC, Karthik-K-N commented
/cherry-pick release-4.11